services:
  discovery-service:
    build: ./Service
    container_name: discovery-service
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 5s

  config-server:
    build: ./Config
    container_name: config-server
    ports:
      - '9999:9999'
    expose:
      - '9999'
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
#    IL FAUT REMPLACER LE LOCALHOST PAR LE NOM DU CONTENEUR

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9999/actuator/health"]
      interval: 5s
    depends_on:
      discovery-service:
        condition: service_healthy

  customer-service:
    build : ./Customer-Service
    container_name: customer-service
    ports:
      - '8082:8082'
    expose:
      - '8082'
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://config-server:9999
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 5s
    depends_on:
      config-server:
        condition: service_healthy


  account-service:
    build: ./Account-Service
    container_name: account-service
    ports:
      - '8081:8081'
    expose:
      - '8081'
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://config-server:9999
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 5s
    depends_on:
      customer-service:
        condition: service_healthy


  gateway-service:
    build: ./Gateway-Service
    container_name: gateway-service
    ports:
      - '8888:8888'
    expose:
      - '8888'
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://config-server:9999
    depends_on:
      account-service:
         condition: service_healthy
