services:
  discovery-service:
    build: ./Service
    container_name: ebank-discovery-service
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 5s

  ebank-config-server:
    build: ./Config
    container_name: ebank-config-server
    ports:
      - '9999:9999'
    expose:
      - '9999'
    depends_on:
      discovery-service:
        condition: service_healthy